network:
  version: 2
  ethernets:
    ens33:
      dhcp4: true
    ens37:
      dhcp4: false
    ens38:
      dhcp4: false
    ens39:
      dhcp4: false
  bridges:
    br0:
      interfaces: [ens37, ens38, ens39]
      dhcp4: no
      addresses: [192.168.56.1/24]
