#!/usr/sbin/nft -f

flush ruleset

# Таблица для NAT
table inet nat {
    chain postrouting {
        type nat hook postrouting priority 100;
        oifname "ens33" masquerade
    }
}
# Таблица для фильтрации
table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # Разрешить loopback
        iif "lo" accept

        # Разрешить установленные соединения
        ct state established,related accept

        # Разрешить SSH
        tcp dport 22 accept

        # Разрешить ICMP (ping)
        icmp type echo-request accept
        icmpv6 type echo-request accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;

        # Разрешить форвардинг из внутренней сети во внешнюю
        iifname "br0" oifname "ens33" accept

        # Разрешить ответный трафик из внешней сети
        iifname "ens33" oifname "br0" ct state established,related accept
    }
}
